# General
SPECIAL_FILE: "help.py"
WORK_PATH: ""

# Prompts
MAIN_PROMPT: "Please generate code for the following task..."
SUMMARY_PROMPT: "Provide a summary of this file..."
MAIN_PROMPT_ULTIMATUM: "Limit your response to the full contents of a python script, and nothing else."

# Final Output
OUTPUT_EXAMPLE: "Limit your output strictly to the contents of the file, like this: ```complete contents of file```."
OUTPUT_CHECK_PROMPT: "Examine the following output and determine if 1. The output is complete and 2. The output is limited strictly to the contents of a file. Format your response exactly like this: ```is_limited_to_file_contents:[1/0],is_complete:[1/0]```."
OUTPUT_EXT: ".py"
OUTPUT_FILENAME_APPEND: "-help"

# Prompt-specific Models
MAIN_MODEL: 4
SUMMARY_MODEL: 4
OUTPUT_CHECK_MODEL: 3

# Prompt-specific Temps
MAIN_TEMP: 1
SUMMARY_TEMP: 1
OUTPUT_CHECK_TEMP: .5
