# Monkey Config Defaults
#
# This file is used to set default values for monkey configs.
# It is also the source of truth for all monkey config options, so if you add or alter
# something here, it is written to the MonkeyConfig class and .env.default.
# (you must update .env manually)

# RULES
# - Keys must be SNAKE_CASE
# - Keys with a word-boundaried "PATH" are validated as PATH
# - Keys with a word-boundaried "PROMPT" are validated as PROMPT
# - Keys with a word-boundaried "MODEL" are validated as MODEL
# - Keys with a word-boundaried "TEMP" are validated as TEMP
# - Other keys are validated as primitives (str, bool, etc)
#
#   PATH values will replace 'ROOT_PATH' with your project's root path
#
# - Validation logic is defined in
#   `pack/modules/core/config_mgmt/monkey_config_validations.py`

# General
FILE_TYPES_INCLUDED: ".js,.vue,.php"
FILEPATH_MATCH_EXCLUDED: ".config,.md,.git,migrations,vite,webpack,.txt"
MAX_TOKENS: 4000
FILE_SELECT_MAX_TOKENS: 3000
SPECIAL_FILE_PATH: "help.py"
WORK_PATH: "ROOT_PATH/stor/usr/default_work_path"

# Prompts
MAIN_PROMPT: "Please generate code for the following task..."
SUMMARY_PROMPT: "Provide a summary of this file..."
MAIN_PROMPT_ULTIMATUM: "Limit your response to the full contents of a python script, and nothing else."

# Output Checks
CHECK_OUTPUT: False
OUTPUT_TRIES_LIMIT: 1
OUTPUT_EXAMPLE_PROMPT: "Limit your output strictly to the contents of the file, like this: ```complete contents of file```."
OUTPUT_CHECK_PROMPT: "Examine the following output and determine if 1. The output is complete and 2. The output is limited strictly to the contents of a file. Format your response exactly like this: ```is_limited_to_file_contents:[1/0],is_complete:[1/0]```."

# Output
OUTPUT_PATH: "ROOT_PATH/stor/usr/default_output_path"
OUTPUT_EXT: ".py"
OUTPUT_FILENAME_APPEND: ""
OUTPUT_REMOVE_STRINGS: "```,```python"
SKIP_EXISTING_OUTPUT_FILES: True

# Prompt-specific Models
MAIN_MODEL: 4
SUMMARY_MODEL: 4
OUTPUT_CHECK_MODEL: 3

# Prompt-specific Temps
MAIN_TEMP: 1.0
SUMMARY_TEMP: 1.0
OUTPUT_CHECK_TEMP: .5
